### ISSUE TITLE
Problem on Windows

### ISSUE THREAD

**Issue by amotl** [Entepotenz/change-string-case-action-min-dependencies#4]
Hi there.

First things first: Thanks a stack for conceiving this excellent workflow action.

Here, on [GHA run #27119893302](https://github.com/crate-workbench/cratedb-toolkit/actions/runs/9822786857/job/27119893302?pr=175), it appears like the recipe is not able to launch properly on Windows.
```
Run Entepotenz/change-string-case-action-min-dependencies@v1
Run python3 D:\a\_actions\Entepotenz\change-string-case-action-min-dependencies\v1/src/script.py 'Windows-X64'
C:\hostedtoolcache\windows\Python\3.12.4\x64\python3.exe: can't open file 'D:\\a\\cratedb-toolkit\\cratedb-toolkit\\a_actionsEntepotenzchange-string-case-action-min-dependenciesv1\\src\\script.py': [Errno 2] No such file or directory
```

With kind regards,
Andreas.

**Comment by Entepotenz** [comment]
Thanks for your nice report. I created a new version v1.2.0 to fix your issue.
I added another test run for windows as well.

If you are interested in the changes you can check them out here: https://github.com/Entepotenz/change-string-case-action-min-dependencies/commit/969e3c6b2477c0442b9037ee9d699cb837e4b032

Kind regards,
Florian
